config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  #resources :topics
  #get 'topics/new', to: "topics#new"
  #post "topics", to: "topics#create"
  
  get 'session/new'
  # get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/index'

  resources :users
  resources :sessions
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/classworks',        to: 'classworks#home'
  get  '/classworks/index', to: 'classworks#index'
  get '/classworks/search', to: 'classworks#search'
  get  '/classworks/:id',   to: 'classworks#show'
  
  get '/classworks/:id/comments/new',         to: 'comments#new',             as:'comments_new'
  get '/classworks/:id/comments',             to: 'comments#index',           as:'comments_index'
  post '/classworks/:id/comments_comment',    to: 'comments#create_comment',  as:'comments_create'
  post '/classworks/:id/comments_picture',    to: 'comments#create_picture',  as:'pictures_create'
  get '/classworks/:id/pictures',             to: 'pictures#index',           as:'pictures_index'
  
  get '/favorites/index', to: 'favorites#index'
  post '/favorites',      to: 'favorites#create'
  delete '/favorites',    to: 'favorites#destroy'
  #resources :classworks
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classwork.rb
class Classwork < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :pictures
  has_many :favorites
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  # validates :picture, presence: true
  belongs_to :classwork
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :classwork
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, presence: true
  
  belongs_to :classwork
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  #validates :description, presence: true
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord    
  validates :name, presence: true, length: { minimum: 1, maximum: 225 }
  validates :email, {presence: true, length: { maximum: 300 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }}
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, {presence: true, length: { minimum: 1, maximum: 32 }, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数を両方含む必要があります'}}
  has_secure_password 
  
  has_many :classworks
  has_many :comments
  has_many :pictures
  has_many :favorites
  has_many :favorite_classworks, through: :favorites, source: :classwork
end

app/controllers/classworks_controller.rb
class ClassworksController < ApplicationController
    
    def home
        render "classworks/home"
    end
    
    def search
        
       # @classwork = Classwork.where('class_name LIKE ?': "%#{params[:class_name]}%", 'professor_name LIKE?': "%#{params[:professor_name]}%" ,w_day : params[:w_day], period: params[:period])
       # @classwork = Classwork.where('class_name LIKE ? and professor_name LIKE ?' , "%#{params[:class_name]}%" , "%#{params[:professor_name]}%" ).where(w_day: params[:w_day], period: params[:period])
       # @classwork = Classwork.where('class_name LIKE ? and professor_name LIKE ? and w_day = ? and period = ?' , "%#{params[:class_name]}%" , "%#{params[:professor_name]}%",  params[:w_day], params[:period])
       # @classwork = Classwork.where('class_name LIKE ? and professor_name LIKE ?' , "%#{params[:class_name]}%" , "%#{params[:professor_name]}%" ).where(w_day: params[:w_day], period: params[:period])
        query = ""
        values = []
        if params[:w_day].present?
            query += "w_day = ? and "   #select * from "テーブル名"　where "カラム名" = "値(?/LIKE)" and "カラム名" = "値(?/LIKE)"
            values.push(params[:w_day])
        end
        if params[:period].present?
            query += "period = ? and " 
            values.push(params[:period])
        end
        if params[:class_name].present?
            query += "class_name LIKE ? and "
            values.push("%#{params[:class_name]}%")
        end
        if params[:professor_name].present?
            query += "professor_name LIKE ? and "
            values.push("%#{params[:professor_name]}%")
            # "%" + params[:professor_name] + "%"
        end
        query = query.sub(/\sand\s\z/, "")

        @classwork = Classwork.where(query, *values)
        # binding.pry
        render "classworks/index"
    end
    
    def show
        @classwork = Classwork.find_by(id: params[:id])
        if @classwork.nil?
            abort 404
        end
        @favorite = Favorite.find_by(classwork_id: @classwork.id, user_id: current_user.id)
        render "classworks/show"
    end
    
     def index
        render "classworks/index"
     end
    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end
  
  def index
    @comments = Comment.all
  end
  
  def create_comment
    @comment = Comment.new(user_id:current_user.id, classwork_id:params[:id], **comment_params )
    #binding.pry
    if @comment.save
      redirect_to comments_index_path, success: "コメントの投稿に成功しました"
    else
      flash.now[:danger] = "コメントの投稿に失敗しました"
      render :new
    end
    
  end
  
  def create_picture
    @picture = Picture.new(user_id:current_user.id, classwork_id:params[:id], **picture_params)
    #binding.pry
    if @picture.save
      redirect_to pictures_index_path, success: "画像の投稿に成功しました"  
    else
      flash.now[:danger] = "画像の投稿に失敗しました"
      render :new
    end
  end
  
  
  
  
  # def create
  #   #binding.pry
  #   if params[:comment].present?
  #     @comment = Comment.new(user_id:current_user.id, classwork_id:params[:id], content:params[:comment])
  #     @comment.save
  #   end
  #   if params[:picture].present?
  #     @picture = Picture.new(user_id:current_user.id, classwork_id:params[:id], description:params[:description], image:params[:picture])
  #     @picture.save
  #   end
  #   redirect_to comments_index_path
  # end
  
  
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
  
  private
  def picture_params
    params.require(:picture).permit(:description, :image)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end
  
  def help
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: "画像が投稿されました"
    else
      flash.now[:danger] = "画像の投稿に失敗しました"
      render :new
    end
  end
  
  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    #render "users/new"
  end
  
  def create
    #@user = User.new(name: params[:user][:name], email: params[:user][:email])
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path,success: '登録が完了しました'
    else
      flash.now[:danger] = '登録に失敗しました'
      render "users/new"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classworks_helper.rb
module ClassworksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/classworks/classwork.html.erb
<div class="top-hero-wrapper text-center">
   <div class="conteiner top-hero-container">
    <h1 class="text-white">Hello guys!</h1>
    <h2 class="text-white">気になる講義を探してみよう</h2>
    <div class="container">
      
      <div class="search-bar">aaaa</div>
      
      <div class="search-area">
        <%= form_with url: root_path, method: "GET"  do |f| %>
        <table>
          <tr>
            <th>講義名</th>
            <td><%= f.text_field :class_name %></td>
          </tr>
          <tr>
            <th>教員名</th>
            <td><%= f.text_field :professor_name %></td>
          </tr>
          <tr>
            <th>曜日</th>
            <td><%= f.select :w_day, ["月", "火", "水", "木", "金", "土"] %></td>
          </tr>
          <tr>
            <th>時限</th>
            <td><%= f.select :period, ["1", "2", "3", "4", "5", "6"] %></td>
          </tr>
        </table>
        
        
        <div class="search-btn">
          <%= f.submit 'Search', class: 'btn btn-block btn-white' %>
        </div>
        <% end %>
        
        </div>
    </div>
  </div>
</div> 

app/views/classworks/home.html.erb
<div class="top-hero-wrapper text-center">
   <div class="conteiner top-hero-container">
    <h1 class="text-white">Hello guys!</h1>
    <h2 class="text-white">気になる講義を探してみよう</h2>
    <div class="container">
      
      <div class="search-bar">aaaa</div>
      
      <div class="search-area">
        <%= form_with url: classworks_search_path, method: "GET", local: true  do |f| %>
        <table>
          <tr>
            <th>講義名</th>
            <td><%= f.text_field :class_name %></td>
          </tr>
          <tr>
            <th>教員名</th>
            <td><%= f.text_field :professor_name %></td>
          </tr>
          <tr>
            <th>曜日</th>
            <td><%= f.select :w_day, ["月", "火", "水", "木", "金", "土"], {include_blank: "曜日を選択しない"} %></td>
          </tr>
          <tr>
            <th>時限</th>
            <td><%= f.select :period, ["1", "2", "3", "4", "5", "6"], {include_blank: "時限を選択しない"} %></td>
          </tr>
        </table>
        
        
        <div class="search-btn">
          <%= f.submit 'Search', class: 'btn btn-block btn-white' %>
        </div>
        <% end %>
        
        </div>
    </div>
  </div>
</div> 

app/views/classworks/index.html.erb
<div class="top-hero-wrapper text-center">
   <div class="conteiner top-hero-container">
      <h1 class="text-white">Hello guys!</h1>
      <h2 class="text-white">検索結果一覧</h2>
      <div class="container">
         <% @classwork.each do |classwork| %>
            <!--<a href="" class="btn btn--orange">PUSH</a>-->
            
            <div class="btn btn--Individual-classwork">
               <%= link_to("/classworks/#{classwork.id}", class: "text-white") do %>
                  <%= classwork.class_name %>
                  <%= classwork.professor_name %>
                  <%= classwork.w_day %>
                  <%= classwork.period %>
               <% end %>
            </div>
               
         
         <% end %>
         
      </div>
   </div>
</div>

app/views/classworks/show.html.erb
<div class="top-hero-wrapper text-center">
   <div class="conteiner top-hero-container">
      <h1 class="text-white">Hello guys!</h1>
      <h2 class="text-white">個別授業ページ</h2>
      <div class="favorite-count text-white">
         <h3>この講義のお気に入り登録者数=><%= @classwork.favorites.count %></h3>
      </div>
      <i class="fab fa-contao fa-9x fa-spin fa-border fontawesome-color"></i>
      <div class="individual text-white">
         <%= @classwork.class_name %>
         <%= @classwork.professor_name %>
         <%= @classwork.w_day %>
         <%= @classwork.period %>
      </div>
      <h2 class="text-white">講義紹介</h1>
         <div class="text-introduction text-white">
            <%= @classwork.introduction %>
         </div>
      <div class="comment-btn flex-center">
         <!--<div>-->
            <!--< link_to 'この講義をお気に入りに登録する', favorite_index_path, class: 'btn btn-block btn-white flex-center' %>-->
         <!--</div>-->
         <div class="col-md-3">
            <%= link_to '投稿されたコメント', comments_index_path, class: 'btn btn-block btn-white flex-center' %>
         </div>
         <div class="col-md-3">
            <%= link_to 'コメントを投稿する', comments_new_path, class: 'btn btn-block btn-white flex-center' %>
         </div>
         <div class="col-md-3">
            <%= link_to '過去問', pictures_index_path, class: 'btn btn-block btn-white flex-center' %>
         </div>
         <div class="col-md-3">
            <% if @favorite.blank? %>
               <%= form_with(url:favorites_path, local: true, method: "POST", class: 'btn  btn-block btn-white flex-center border-none') do |f| %>
                  <%= f.hidden_field :classwork_id, value: @classwork.id %>
                  <%= f.submit '後で見るに登録', class: 'btn btn-block btn-white' %>
               <% end %>
            <% else %>
               <%= form_with(url:favorites_path, local: true, method: "DELETE", class: 'btn  btn-block btn-white flex-center border-none') do |f| %>
                  <%= f.hidden_field :classwork_id, value: @classwork.id %>
                  <%= f.submit '後で見るに登録を解除', class: 'btn btn-block btn-white' %> 
               <% end %>
            <% end %>
         </div>
      </div>
   </div>
</div>