config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  #resources :topics
  #get 'topics/new', to: "topics#new"
  #post "topics", to: "topics#create"
  
  get 'session/new'
  # get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/index'

  resources :users
  resources :sessions
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/classworks',        to: 'classworks#home'
  get  '/classworks/index', to: 'classworks#index'
  get '/classworks/search', to: 'classworks#search'
  get  '/classworks/:id',   to: 'classworks#show'
  
  get '/classworks/:id/comments/new',         to: 'comments#new',             as:'comments_new'
  get '/classworks/:id/comments',             to: 'comments#index',           as:'comments_index'
  post '/classworks/:id/comments_comment',    to: 'comments#create_comment',  as:'comments_create'
  post '/classworks/:id/comments_picture',    to: 'comments#create_picture',  as:'pictures_create'
  get '/classworks/:id/pictures',             to: 'pictures#index',           as:'pictures_index'
  
  get '/favorites/index', to: 'favorites#index'
  post '/favorites',      to: 'favorites#create'
  delete '/favorites',    to: 'favorites#destroy'
  #resources :classworks
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classwork.rb
class Classwork < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :pictures
  has_many :favorites
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  # validates :picture, presence: true
  belongs_to :classwork
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :classwork
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, presence: true
  
  belongs_to :classwork
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  #validates :description, presence: true
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord    
  validates :name, presence: true, length: { minimum: 1, maximum: 225 }
  validates :email, {presence: true, length: { maximum: 300 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }}
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, {presence: true, length: { minimum: 1, maximum: 32 }, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数を両方含む必要があります'}}
  has_secure_password 
  
  has_many :classworks
  has_many :comments
  has_many :pictures
  has_many :favorites
  has_many :favorite_classworks, through: :favorites, source: :classwork
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end
  
  def help
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    #render "users/new"
  end
  
  def create
    #@user = User.new(name: params[:user][:name], email: params[:user][:email])
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path,success: '登録が完了しました'
    else
      flash.now[:danger] = '登録に失敗しました'
      render "users/new"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classworks_helper.rb
module ClassworksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campus Design</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "campus-design.jpeg", class: "navbar-brand" %></span>
        <% end %>
          
          <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
              <li>
                <%= link_to favorites_index_path do %>
                  <%= image_tag "heart.png" %>
                  <!--<i class="fas fa-bookmark"></i>-->
                <% end %>
              </li>
              <li>
                <%= link_to logout_path, method: :delete do %>
                  <%= image_tag "logout.png" %>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_path do %>
                  <%= image_tag "register.png" %>
                <% end %>
              </li>
          <% else %>
              <li>
                <%= link_to login_path do %>
                  <%= image_tag "login.png" %>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000)
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
    <div class="container top-hero-container">
        <h1 class="text-white">Make you Happy</h1>
        <h2 class="text-white">Cumpus Design is a service that you can get a lot of information about AGU classes </h2>
        <div class="container">
        <div class="row flex-center">
            <div class="col-md-3">
                <%= link_to 'Sing up', new_user_path, class: 'btn btn-block btn-white' %>
            </div>
            <div class="col-md-3">
                <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
            </div> 
        </div>
        </div>
    </div>
</div>